### ISSUE TITLE
Not fully working on iOS 8.4

### ISSUE THREAD

**Issue by adrianmkofficial** [numee/Cordova-Ready-iBeacon#1]
Hi,

I tried using this Plugin, but it fails to find my beacon. I typed in the UUID and Major / Minor but the app doesn't display an alert, even though it's right next to the beacon. Bluetooth is enabled. I'm using the example Project, almost unmodified.

Any help?

Also XCode keeps posting this over and over in the Log:

     HelloCordova[42913:1593298] Loading Location authentication...
     HelloCordova[42913:1593298] This app is authorized to use location.

**Comment by RomainFallet** [comment]
Hello,

I just test the example on iOS 8.4 and it's working for me.
Be sure that you have added all the Cordova plugins required with the cordova plugin add command.
Be sure that you have specified the correct infos and give an ID to each beacon in the ibeacon.initialize method.
Note that it does not work on emulator, you have to test it on a real device.

On which device did you tested ?

If this did not work, feel free to send me a zip of your project.

Best.

**Comment by adrianmkofficial** [comment]
Thanks for the quick reply.

Unfortunately none of the tips mentioned helped me. I re-downloaded your Example Project, removed and reinstalled all plugins, added Cordova Platform iOS, changed the script in Index.html to reflect the UUID of my beacon and the major / minor numbers as well, and then ran the App successfully on my iPhone 6, iOS 8.4. The Beacon is right next to the iPhone and all I see is "Look at my awesome iBeacon app!" but no alert popping up. There is nothing in the WebView Console either, no Errors, no Warnings.

**Comment by RomainFallet** [comment]
Send me your sample project, I will compare it with mine.

**Comment by adrianmkofficial** [comment]
I have forked your repo and uploaded my changes there. Basically I just changed the IDs and the rest remains untouched. Like I said, no alerts, whatsoever. The Beacon is right next to the iPhone... :/

**Comment by RomainFallet** [comment]
I was about to ask you the same question. I use also the last version of Cordova : 5.1.1.
What is your OS X and Xcode version ?

**Comment by RomainFallet** [comment]
Did you enabled locations services and authorize the application to access location services ?

**Comment by RomainFallet** [comment]
The last thing I thing about is the ibeacon itself. Do you have the ability to test on another ibeacon ?
Personnaly, I use this one : http://ibeacon.accent-systems.com/shop/ibks105-kits.

Let me know.

**Comment by adrianmkofficial** [comment]
Hi, thank you for your help and incredible work on the Project.
After cracking my head open and trying out Beacons on my iPad, I realised that it must be something specific to my iPhone 6 Set-up. Both the iPad and iPhone were jailbroken, but the iPad was showing Beacons effortlessly. Further investigating the issue led me to the fact I had a Tool from Cydia installed called "Fake GPS". Apparently it was causing the iPhone to not see Beacons, even though it was turned off. Disabling the Cydia Substrate Library of this Tool made your project work flawlessly. Thank you very much again (:
